### PR TITLE
feat/add-html-pdf-windows

### PR DESCRIPTION
**Pull request by iangohy**
1. Created a batch file `convert_to_html_pdf.bat` to mimic functionality of `convert_to_html.sh` for Windows users.

2. Updated `convert_to_html.sh` to shift the pdf creation outside of the loop to minimise unnecessary conversions. 
@rphly do let me know if there are any reasons you placed the `python3 convert_to_pdf.py` within the loop, I'll be happy to revert the file.

3. Updated the output folder with the current version of the notes.

### CODE REVIEW

**Comment by kurniawano** [comment]
@iangohy , I think the file `convert_to_pdf.py` assumes that HTML files are produced so it has to be run after running the `jupyter nbconvert`. If we put it outside the if-else (not loop), it means that it is possible to run the conversion from HTML to PDF without having the updated HTML. So I think it is better to put it inside the if body.

**Comment by iangohy** [comment]
@kurniawano I see your concern of converting the HTML to PDF without updated HTML. I moved the conversion outside of the loop as I noticed the python script attempts to convert all files ending in `.html` in the outputs folder, not just the freshly converted file. Maybe I'll rewrite the python script to accept a filename argument so that the script will only convert the freshly generated `.html` file instead of all `.html` files.

**Comment by iangohy** [comment]
@kurniawano I've made the edit to the python script only convert a single file after obtaining the latest `.html` in the script. Updated both the bash script and batch file. Do let me know if there are any concerns, thanks!

**Comment by kurniawano** [comment]
Since we are moving to html based in the website. We will close this.

**Pull request closed without merging**
