### PR TITLE
feat/add-html-pdf

### PR DESCRIPTION
**Pull request by rphly**
adding output folder so students can access via ipad to take notes

### CODE REVIEW

**Comment by rphly** [comment]
@kurniawano

**Review by kurniawano — CHANGES_REQUESTED** [review]
@rphly , Thanks for the good suggestion. I normally don't put binary file like PDF into the repository, but I like the idea of students can access it from other devices. Before that, can you help me put some note into the README on how to run the `convert_to_pdf.py` for people to know how to generate these PDFs and HTMLs? Then, I will accept the changes.

**Comment by rphly** [comment]
got it, thanks Prof. forgot to push the bash script to get HTML too. will add requirements and readme.

**Comment by rphly** [comment]
Added requirements, edited readme and added scripts to the outer folder instead

**Comment by kurniawano** [comment]
Thanks @rphly .

**Pull request merged**
